name: hl2mp
services:
  server:
    container_name: hl2mp
    image: alpaka/hl2mp:latest
    build:
      context: build
      dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/local/containers/volumes/hl2mp/game:/home/steam/hl2mp-dedicated
    environment:
      - STEAMAPPID=232370
      - STEAMAPP=hl2mp
      - SRCDS_IP=0.0.0.0
      - SRCDS_MAXPLAYERS=8
      - SRCDS_STARTMAP=dm_lockdown
      - SRCDS_PW=
      - SRCDS_RCONPW=
      - SRCDS_HOSTNAME="Alpaka HL2MP Server"
    restart: unless-stopped
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
      - "27020:27020/udp"
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 10G
    networks:
      - default
      - shared
  playit:
    container_name: playit
    image: ghcr.io/mafen/playit-docker:latest
    restart: unless-stopped
    depends_on:
      - server
    environment:
      - SECRET_KEY=2dd280465443e3f330d6a0eafca64ff200695c9efc429ab17ec6b71dacf6f1be
    volumes:
      - /usr/local/containers/volumes/hl2mp/playit.toml:/etc/playit/playit.toml
    networks:
      - default
      - shared
networks:
  shared:
    external: true
